### ISSUE TITLE
[sort of irrelevant] The rest of your work on this device is gone. 

### ISSUE THREAD

**Issue by MrSenshi** [hak86/android_kernel_huawei_prague#1]
You seem to have placed a lot of ROMs and recoveries for the P8 Lite (PRA-LX1) on Basketbuild and they are no longer available to anyone. (404)

I'm very sorry for saying this via a Github issue, my friends phone is unusable and we have no idea what else to do. We unlocked the bootloader using a third party tool and tried to flash some ROMs, only to realize they require EMUI8, which we don't have. All other tools for fixing this and ROMs that work on EMUI5 have broken links or simply don't work. To make things worse, HuRUpdater just flopped on us. If you could reupload some of your previous work that would be great. Hope you understand. (p.s. Sorry for this random request, I know you are probably busy with other stuff)

**Comment by hak86** [comment]
first of all, pra-lx1 has emui 8, just look around firmware finder. secondly I'm not working on emui5 anymore. my device is bricked (imei and bootloader can't be unlocked) my roms for emui8 are here https://www.haky86.com/pra/emui-8/ I made 7 bootable roms. many will come later

**Comment by MrSenshi** [comment]
Hi, I understand, thanks anyway! BTW, you can still unlock Huawei devices bootloader unofficially with DC Unlocker, even though Huawei does not distribute unlock codes any longer. It's paid but actually works. Tested this February.

**Comment by hak86** [comment]
I know even after board software? if yes I'll do again because gimme wrong password.
