### ISSUE TITLE
sorry in advance! 

### ISSUE THREAD

**Issue by LENZFLIKER** [hak86/android_kernel_huawei_prague#1]
Appreciate your contributions on XDA.
The site you uploaded TWRP for PRA-LX seem to be [down ](https://basketbuild.com/devs/haky86/HuaweiP8Lite2017/TWRP)and there is no other way to download it. XDA says your TWRP is the only one that works with PRA-LX2 + Android 7.0
Could you reup it here?

**Comment by hak86** [comment]
@LENZFLIKER sorry for the late answer, check my https://sourceforge.net/projects/hi6250/files/Emui-8.x/TWRP/
they are bit "buggy".

**Comment by LENZFLIKER** [comment]
Thank you Hak86!
